// src/components/signup/signup-form.tsx
import { cn } from '@/lib/utils';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { useForm } from '@tanstack/react-form';
import { supabase } from '@/supabase/supabase-client';
import { toast } from 'sonner';
import { useNavigate } from '@tanstack/react-router';
import React, { useState } from 'react';
import { Checkbox } from '@/components/ui/checkbox';

export default function SignUpForm({
  setShowLogIn,
  className,
  ...props
}: {
  setShowLogIn: React.Dispatch<React.SetStateAction<boolean>>;
} & React.ComponentProps<'form'>) {
  const navigate = useNavigate();
  const [showPassword, setShowPassword] = useState(false);
  const form = useForm({
    defaultValues: {
      name: '',
      email: '',
      password: '',
    },

    onSubmit: async () => {
      const { error } = await supabase.auth.signUp({
        email: form.getFieldValue('email'),
        password: form.getFieldValue('password'),
        options: {
          data: { name: form.getFieldValue('name') },
        },
      });
      if (error) return toast.error('Error creating user');
      toast.message(`Welcome, ${form.getFieldValue('name')}`);
      navigate({ to: '/dashboard' });
      form.reset();
    },
  });
  async function handleOAuth() {
    const { data, error } = await supabase.auth.signInWithOAuth({
      provider: 'google',
    });
    if (error) return toast.error('Error signing user');
    console.log('google.sign in', data);
  }
  return (
    <div>
      <form
        onSubmit={(e) => {
          e.preventDefault();
          e.stopPropagation();
          form.handleSubmit();
        }}
        className={cn('flex flex-col gap-6', className)}
        {...props}
      >
        <div className="flex flex-col items-center gap-2 text-center">
          <h1 className="text-2xl font-bold uppercase">
            Welcome to Personal Finance
          </h1>
          <p className="text-muted-foreground text-sm text-balance">
            Control your finance like it's in your pocket
          </p>
        </div>
        <div className="grid gap-3">
          <Label htmlFor="name">Name</Label>
          <form.Field
            name="name"
            validators={{
              onChange: ({ value }) =>
                !value ? 'A name is required' : undefined,
              onChangeAsyncDebounceMs: 500,
              onChangeAsync: async ({ value }) => {
                await new Promise((resolve) => setTimeout(resolve, 1000));
                return value.includes('error') && 'No "error" allowed in name';
              },
            }}
            children={(field) => {
              return (
                <div className="flex flex-col gap-1.5">
                  <Input
                    id="name"
                    placeholder="John Doe"
                    onChange={(e) => field.handleChange(e.target.value)}
                    className=" "
                  />
                  {!field.state.meta.isValid && (
                    <small className="text-destructive">
                      {field.state.meta.errors.join(',')}
                    </small>
                  )}
                </div>
              );
            }}
          />{' '}
        </div>

        <div className="grid gap-3">
          <Label htmlFor="email">Email</Label>
          <form.Field
            name="email"
            validators={{
              onChange: ({ value }) =>
                !value ? 'An email is required' : undefined,
              onChangeAsyncDebounceMs: 500,
              onChangeAsync: async ({ value }) => {
                await new Promise((resolve) => setTimeout(resolve, 1000));
                return value.includes('error') && 'No "error" allowed in email';
              },
            }}
            children={(field) => {
              return (
                <div className="flex flex-col gap-1.5">
                  <Input
                    id="email"
                    placeholder="example@example.com "
                    onChange={(e) => field.handleChange(e.target.value)}
                    className=" "
                  />
                  {!field.state.meta.isValid && (
                    <small className="text-destructive">
                      {field.state.meta.errors.join(',')}
                    </small>
                  )}
                </div>
              );
            }}
          />{' '}
        </div>
        <div className="grid gap-3">
          <div className="flex items-center">
            <Label htmlFor="password">Password</Label>
          </div>
          <form.Field
            name="password"
            validators={{
              onChange: ({ value }) =>
                !value
                  ? 'Password is required'
                  : value.length < 6
                    ? 'Password must be greater than 6 characters'
                    : undefined,
              onChangeAsyncDebounceMs: 500,
              onChangeAsync: async ({ value }) => {
                await new Promise((resolve) => setTimeout(resolve, 1000));
                return (
                  value.includes('error') && 'No "error" allowed in password'
                );
              },
            }}
            children={(field) => {
              return (
                <div className="flex flex-col gap-1.5">
                  <Input
                    id="password"
                    type={`${showPassword ? 'text' : 'password'}`}
                    onChange={(e) => field.handleChange(e.target.value)}
                    placeholder="Enter your password here"
                  />
                  <div className="flex gap-2 items-center">
                    <Checkbox onClick={() => setShowPassword(!showPassword)} />{' '}
                    <Label>Show password</Label>
                  </div>

                  {!field.state.meta.isValid && (
                    <small className="text-destructive">
                      {field.state.meta.errors.join(',')}
                    </small>
                  )}
                </div>
              );
            }}
          />
        </div>
        <form.Subscribe
          children={() => (
            <Button type="submit" className="w-full">
              Sign up
            </Button>
          )}
        />
      </form>
      <div className="grid gap-6 py-2">
        <div className="after:border-border relative text-center text-sm after:absolute after:inset-0 after:top-1/2 after:z-0 after:flex after:items-center after:border-t">
          <span className="bg-background text-black dark:text-muted-foreground relative z-10 px-2">
            Or continue with
          </span>
        </div>
        <Button
          variant="outline"
          onClick={handleOAuth}
          className="w-full cursor-pointer"
        >
          <svg
            viewBox="-0.5 0 48 48"
            version="1.1"
            xmlns="http://www.w3.org/2000/svg"
            xmlnsXlink="http://www.w3.org/1999/xlink"
            fill="#000000"
          >
            <g id="SVGRepo_bgCarrier" strokeWidth="0"></g>
            <g
              id="SVGRepo_tracerCarrier"
              strokeLinecap="round"
              strokeLinejoin="round"
            ></g>
            <g id="SVGRepo_iconCarrier">
              {' '}
              <title>Google-color</title> <desc>Created with Sketch.</desc>{' '}
              <defs> </defs>{' '}
              <g
                id="Icons"
                stroke="none"
                strokeWidth="1"
                fill="none"
                fillRule="evenodd"
              >
                {' '}
                <g id="Color-" transform="translate(-401.000000, -860.000000)">
                  {' '}
                  <g id="Google" transform="translate(401.000000, 860.000000)">
                    {' '}
                    <path
                      d="M9.82727273,24 C9.82727273,22.4757333 10.0804318,21.0144 10.5322727,19.6437333 L2.62345455,13.6042667 C1.08206818,16.7338667 0.213636364,20.2602667 0.213636364,24 C0.213636364,27.7365333 1.081,31.2608 2.62025,34.3882667 L10.5247955,28.3370667 C10.0772273,26.9728 9.82727273,25.5168 9.82727273,24"
                      id="Fill-1"
                      fill="#FBBC05"
                    >
                      {' '}
                    </path>{' '}
                    <path
                      d="M23.7136364,10.1333333 C27.025,10.1333333 30.0159091,11.3066667 32.3659091,13.2266667 L39.2022727,6.4 C35.0363636,2.77333333 29.6954545,0.533333333 23.7136364,0.533333333 C14.4268636,0.533333333 6.44540909,5.84426667 2.62345455,13.6042667 L10.5322727,19.6437333 C12.3545909,14.112 17.5491591,10.1333333 23.7136364,10.1333333"
                      id="Fill-2"
                      fill="#EB4335"
                    >
                      {' '}
                    </path>{' '}
                    <path
                      d="M23.7136364,37.8666667 C17.5491591,37.8666667 12.3545909,33.888 10.5322727,28.3562667 L2.62345455,34.3946667 C6.44540909,42.1557333 14.4268636,47.4666667 23.7136364,47.4666667 C29.4455,47.4666667 34.9177955,45.4314667 39.0249545,41.6181333 L31.5177727,35.8144 C29.3995682,37.1488 26.7323182,37.8666667 23.7136364,37.8666667"
                      id="Fill-3"
                      fill="#34A853"
                    >
                      {' '}
                    </path>{' '}
                    <path
                      d="M46.1454545,24 C46.1454545,22.6133333 45.9318182,21.12 45.6113636,19.7333333 L23.7136364,19.7333333 L23.7136364,28.8 L36.3181818,28.8 C35.6879545,31.8912 33.9724545,34.2677333 31.5177727,35.8144 L39.0249545,41.6181333 C43.3393409,37.6138667 46.1454545,31.6490667 46.1454545,24"
                      id="Fill-4"
                      fill="#4285F4"
                    >
                      {' '}
                    </path>{' '}
                  </g>{' '}
                </g>{' '}
              </g>{' '}
            </g>
          </svg>
          Google{' '}
        </Button>
      </div>
      <div className="text-center flex mx-auto items-center justify-center gap-2 text-sm">
        Already have an account?{' '}
        <p
          onClick={() => setShowLogIn(true)}
          className="underline cursor-pointer underline-offset-4"
        >
          Login
        </p>
      </div>
    </div>
  );
}

// src/lib/components/forms/signup-form.svelte
<script lang="ts">
	import { cn } from "$lib/utils.js";
	import { Button } from "$lib/components/ui/button/index.js";
	import * as Card from "$lib/components/ui/card/index.js";
	import * as Field from "$lib/components/ui/field/index.js";
	import { Input } from "$lib/components/ui/input/index.js";
	import type { HTMLAttributes } from "svelte/elements";
    import { authClient } from "../../../auth-client";
    import { toast } from "svelte-sonner";
    import { goto } from "$app/navigation";

	let { class: className, ...restProps }: HTMLAttributes<HTMLDivElement> = $props();
  let fullName = $state('');
	let email = $state('');
	let password = $state('');
	let confirmPassword = $state('');

  async function handleSubmit() {
		try {
			const { data, error } = await authClient.signUp.email({
				name: fullName,
				email: email,
				password: password
			});
			if (data?.user) {
				toast.success(`Hello, ${data.user.name} to Alem Guzo`);
				goto('/dashboard');
			}
			if (error) {
				toast.error(`Error, ${error.message}`);
			}
		} catch (error) {
			console.log('Error at Signing up user,', error);
		}
    }

  async function handleGoogleSignup() {
		try {
			await authClient.signIn.social({ provider: 'google', callbackURL: '/dashboard' });
		} catch (error) {
			console.log('Errror occured when signing up with google, ', error);
		}
}

    </script>

<div class={cn("flex flex-col gap-6", className)} {...restProps}>
	<Card.Root class='bg-transparent border-none'>
		<Card.Header class="text-center">
			<Card.Title class="text-xl">Create your account</Card.Title>
			<Card.Description>Enter your email below to create your account</Card.Description>
		</Card.Header>
		<Card.Content>
			<form>
				<Field.Group>
					<Field.Field>
						<Field.Label for="name">Full Name</Field.Label>
						<Input id="name" type="text" placeholder="John Doe" required bind:value={fullName} />
					</Field.Field>
					<Field.Field>
						<Field.Label for="email">Email</Field.Label>
						<Input id="email" type="email" placeholder="m@example.com" required bind:value={email} />
					</Field.Field>
					<Field.Field>
						<Field.Field class="grid grid-cols-2 gap-4">
							<Field.Field>
								<Field.Label for="password">Password</Field.Label>
								<Input id="password" type="password" required bind:value={password} />
							</Field.Field>
							<Field.Field>
								<Field.Label for="confirm-password">Confirm Password</Field.Label>
								<Input id="confirm-password" type="password" required bind:value={confirmPassword}/>
							</Field.Field>
						</Field.Field>
						<Field.Description>Must be at least 8 characters long.</Field.Description>
					</Field.Field>
					<Field.Field>
						<Button type="submit" onclick={handleSubmit}>Create Account</Button>
			<Field.FieldSeparator class='py-4'>Or</Field.FieldSeparator>
			<Field.Field class="grid gap-4 pt-4">
				<Button variant="outline" type="button" onclick={handleGoogleSignup}>
					<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
						<path
							d="M12.48 10.92v3.28h7.84c-.24 1.84-.853 3.187-1.787 4.133-1.147 1.147-2.933 2.4-6.053 2.4-4.827 0-8.6-3.893-8.6-8.72s3.773-8.72 8.6-8.72c2.6 0 4.507 1.027 5.907 2.347l2.307-2.307C18.747 1.44 16.133 0 12.48 0 5.867 0 .307 5.387.307 12s5.56 12 12.173 12c3.573 0 6.267-1.173 8.373-3.36 2.16-2.16 2.84-5.213 2.84-7.667 0-.76-.053-1.467-.173-2.053H12.48z"
							fill="currentColor"
						/>
					</svg>
					Continue with Google
				</Button>
			</Field.Field>
						<Field.Description class="text-center">
							Already have an account? <a href="/login">Sign in</a>
						</Field.Description>
					</Field.Field>
				</Field.Group>
			</form>
		</Card.Content>
	</Card.Root>
	<Field.Description class="px-6 text-center">
		By clicking continue, you agree to our <a href="#/">Terms of Service</a>
		and <a href="#/">Privacy Policy</a>.
	</Field.Description>
</div>
