// src/lib/components/app-sidebar.svelte
<script lang="ts">
	import CameraIcon from "@tabler/icons-svelte/icons/camera";
	import FileAiIcon from "@tabler/icons-svelte/icons/file-ai";
	import FileDescriptionIcon from "@tabler/icons-svelte/icons/file-description";
	import HelpIcon from "@tabler/icons-svelte/icons/help";
	import InnerShadowTopIcon from "@tabler/icons-svelte/icons/inner-shadow-top";
	import SearchIcon from "@tabler/icons-svelte/icons/search";
	import SettingsIcon from "@tabler/icons-svelte/icons/settings";
	import NavMain from "./nav-main.svelte";
	import NavSecondary from "./nav-secondary.svelte";
	import NavUser from "./nav-user.svelte";
	import * as Sidebar from "$lib/components/ui/sidebar/index.js";
	import type { ComponentProps } from "svelte";
    import {SchoolReportCardIcon, FolderCheckIcon,CheckListIcon,AnalyticsUpFreeIcons,DashboardSquare03Icon,Route01FreeIcons,UserAccountIcon} from '@hugeicons/core-free-icons';
    import NavPlanning from "./nav-planning.svelte";
    import NavInsights from "./nav-insights.svelte";

	const data = {
		user: {
			name: "shadcn",
			email: "m@example.com",
			avatar: "/avatars/shadcn.jpg",
		},
  navInsights:[
 		{
				name: "Analytics",
				url: "#",
				icon: AnalyticsUpFreeIcons ,
			},
      {
        name:'Report',
        url:'#',
        icon:SchoolReportCardIcon
      }
	  ],
		documents: [
			{
				name: "Budget",
				url: "#",
				icon: FolderCheckIcon,
			},
			{
				name: "Plan",
				url: "#",
				icon:CheckListIcon ,
			},
			
		],
	};

  const navMain= [
			{
				title: "Dashboard",
				url: "#",
				icon: DashboardSquare03Icon,
			},
		{
				title: "Track Expenses",
				url: "#",
				icon: Route01FreeIcons,
			},
			{
				title: "Accounts",
				url: "#",
				icon: UserAccountIcon,
			},
		]


	let { ...restProps }: ComponentProps<typeof Sidebar.Root> = $props();
</script>

<Sidebar.Root collapsible="offcanvas" {...restProps}>
	<Sidebar.Header>
		<Sidebar.Menu>
			<Sidebar.MenuItem>
				<Sidebar.MenuButton class="data-[slot=sidebar-menu-button]:p-1.5!">
					{#snippet child({ props })}
						<a href="##" {...props}>
							<span class="text-base font-semibold">Clarity</span>
						</a>
					{/snippet}
				</Sidebar.MenuButton>
			</Sidebar.MenuItem>
		</Sidebar.Menu>
	</Sidebar.Header>
	<Sidebar.Content>
		<NavMain items={navMain} />
		<NavPlanning items={data.documents} />
    <NavInsights items={data.navInsights}/>
	</Sidebar.Content>
	<Sidebar.Footer>
		<NavUser user={data.user} />
	</Sidebar.Footer>
</Sidebar.Root>

// src/components/app-sidebar.tsx
import * as React from 'react';
import {
  IconCamera,
  IconCategory2,
  IconChartBar,
  IconFileAi,
  IconFileDescription,
  IconFolder,
  IconInnerShadowTop,
  IconListDetails,
  IconPlus,
  IconSettings,
} from '@tabler/icons-react';

import { NavMain } from '@/components/nav-main';
import { NavSecondary } from '@/components/nav-secondary';
import { NavUser } from '@/components/nav-user';
import {
  Sidebar,
  SidebarContent,
  SidebarFooter,
  SidebarHeader,
  SidebarMenu,
  SidebarMenuButton,
  SidebarMenuItem,
} from '@/components/ui/sidebar';

const data = {
  user: {
    name: 'amuif',
    email: 'm@example.com',
    avatar: '/avatars/shadcn.jpg',
  },
  navMain: [
    {
      title: 'Home',
      url: '/',
      icon: IconCategory2,
    },
    {
      title: 'Create',
      url: '/create',
      icon: IconPlus,
    },
    {
      title: 'Wallet',
      url: 'wallet',
      icon: IconListDetails,
    },
    {
      title: 'Analytics',
      url: 'analytics',
      icon: IconChartBar,
    },
    {
      title: 'Plans',
      url: 'plans',
      icon: IconFolder,
    },
  ],
  navClouds: [
    {
      title: 'Capture',
      icon: IconCamera,
      isActive: true,
      url: '#',
      items: [
        {
          title: 'Active Proposals',
          url: '#',
        },
        {
          title: 'Archived',
          url: '#',
        },
      ],
    },
    {
      title: 'Proposal',
      icon: IconFileDescription,
      url: '#',
      items: [
        {
          title: 'Active Proposals',
          url: '#',
        },
        {
          title: 'Archived',
          url: '#',
        },
      ],
    },
    {
      title: 'Prompts',
      icon: IconFileAi,
      url: '#',
      items: [
        {
          title: 'Active Proposals',
          url: '#',
        },
        {
          title: 'Archived',
          url: '#',
        },
      ],
    },
  ],
  navSecondary: [
    {
      title: 'Settings',
      url: 'settings',
      icon: IconSettings,
    },
    //   {
    //     title: "Get Help",
    //     url: "#",
    //     icon: IconHelp,
    //   },
  ],
};

export function AppSidebar({ ...props }: React.ComponentProps<typeof Sidebar>) {
  return (
    <Sidebar collapsible="offcanvas" {...props}>
      <SidebarHeader>
        <SidebarMenu>
          <SidebarMenuItem>
            <SidebarMenuButton
              asChild
              className="data-[slot=sidebar-menu-button]:!p-1.5"
            >
              <a href="#">
                <IconInnerShadowTop className="!size-5" />
                <span className="text-base font-semibold">Amuif Plans</span>
              </a>
            </SidebarMenuButton>
          </SidebarMenuItem>
        </SidebarMenu>
      </SidebarHeader>
      <SidebarContent>
        <NavMain items={data.navMain} />
        <NavSecondary items={data.navSecondary} className="mt-auto" />
      </SidebarContent>
      <SidebarFooter>
        <NavUser user={data.user} />
      </SidebarFooter>
    </Sidebar>
  );
}
