// src/components/section-cards.tsx
import { IconTrendingDown, IconTrendingUp } from '@tabler/icons-react';

import { Badge } from '@/components/ui/badge';
import {
  Card,
  CardAction,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';

export function SectionCards() {
  return (
    <div className="grid grid-cols-1 gap-4 px-4  lg:px-6 @xl/main:grid-cols-2 @5xl/main:grid-cols-4">
      <Card className="dark:bg-linear-to-r !dark:from-primary/70 !dark:to-primary bg-primary">
        <CardHeader>
          <CardDescription>Total Revenue</CardDescription>
          <CardTitle className="text-2xl font-semibold tabular-nums @[250px]/card:text-3xl">
            $1,250.00
          </CardTitle>
          <CardAction>
            <Badge className="text-white" variant="outline">
              <IconTrendingUp />
              +12.5%
            </Badge>
          </CardAction>
        </CardHeader>
        <CardFooter className="flex-col items-start gap-1.5 text-sm">
          <div className="line-clamp-1 flex gap-2 font-medium">
            Trending up this month <IconTrendingUp className="size-4" />
          </div>
          <div className="text-muted-foreground">
            Visitors for the last 6 months
          </div>
        </CardFooter>
      </Card>
      <Card className="dark:bg-linear-to-r !dark:from-primary/70 !dark:to-primary bg-primary">
        <CardHeader>
          <CardDescription>New Customers</CardDescription>
          <CardTitle className="text-2xl font-semibold tabular-nums @[250px]/card:text-3xl">
            1,234
          </CardTitle>
          <CardAction>
            <Badge className="text-white" variant="outline">
              <IconTrendingDown />
              -20%
            </Badge>
          </CardAction>
        </CardHeader>
        <CardFooter className="flex-col items-start gap-1.5 text-sm">
          <div className="line-clamp-1 flex gap-2 font-medium">
            Down 20% this period <IconTrendingDown className="size-4" />
          </div>
          <div className="text-muted-foreground">
            Acquisition needs attention
          </div>
        </CardFooter>
      </Card>
      <Card className="dark:bg-linear-to-r !dark:from-primary/70 !dark:to-primary bg-primary">
        <CardHeader>
          <CardDescription>Active Accounts</CardDescription>
          <CardTitle className="text-2xl font-semibold tabular-nums @[250px]/card:text-3xl">
            45,678
          </CardTitle>
          <CardAction>
            <Badge className="text-white" variant="outline">
              <IconTrendingUp />
              +12.5%
            </Badge>
          </CardAction>
        </CardHeader>
        <CardFooter className="flex-col items-start gap-1.5 text-sm">
          <div className="line-clamp-1 flex gap-2 font-medium">
            Strong user retention <IconTrendingUp className="size-4" />
          </div>
          <div className="text-muted-foreground">Engagement exceed targets</div>
        </CardFooter>
      </Card>
      <Card className="dark:bg-linear-to-r !dark:from-primary/70 !dark:to-primary bg-primary">
        <CardHeader>
          <CardDescription>Growth Rate</CardDescription>
          <CardTitle className="text-2xl font-semibold tabular-nums @[250px]/card:text-3xl">
            4.5%
          </CardTitle>
          <CardAction>
            <Badge className="text-white" variant="outline">
              <IconTrendingUp />
              +4.5%
            </Badge>
          </CardAction>
        </CardHeader>
        <CardFooter className="flex-col items-start gap-1.5 text-sm">
          <div className="line-clamp-1 flex gap-2 font-medium">
            Steady performance increase <IconTrendingUp className="size-4" />
          </div>
          <div className="text-muted-foreground">Meets growth projections</div>
        </CardFooter>
      </Card>
    </div>
  );
}

// src/lib/components/section-cards.svelte
<script lang="ts">
  import TrendingDownIcon from "@tabler/icons-svelte/icons/trending-down";
  import TrendingUpIcon from "@tabler/icons-svelte/icons/trending-up";
  import { Badge } from "$lib/components/ui/badge/index.js";
  import * as Card from "$lib/components/ui/card/index.js";
</script>

<div
  class="*:data-[slot=card]:from-primary/5 *:data-[slot=card]:to-card dark:*:data-[slot=card]:bg-card grid grid-cols-1 gap-4 px-4 *:data-[slot=card]:bg-gradient-to-t *:data-[slot=card]:shadow-xs lg:px-6 @xl/main:grid-cols-2 @5xl/main:grid-cols-4"
>
  <Card.Root class="@container/card">
    <Card.Header>
      <Card.Description>Total Revenue</Card.Description>
      <Card.Title
        class="text-2xl font-semibold tabular-nums @[250px]/card:text-3xl"
      >
        $1,250.00
      </Card.Title>
      <Card.Action>
        <Badge variant="outline">
          <TrendingUpIcon />
          +12.5%
        </Badge>
      </Card.Action>
    </Card.Header>
    <Card.Footer class="flex-col items-start gap-1.5 text-sm">
      <div class="line-clamp-1 flex gap-2 font-medium">
        Trending up this month <TrendingUpIcon class="size-4" />
      </div>
      <div class="text-muted-foreground">Visitors for the last 6 months</div>
    </Card.Footer>
  </Card.Root>
  <Card.Root class="@container/card">
    <Card.Header>
      <Card.Description>New Customers</Card.Description>
      <Card.Title
        class="text-2xl font-semibold tabular-nums @[250px]/card:text-3xl"
      >
        1,234
      </Card.Title>
      <Card.Action>
        <Badge variant="outline">
          <TrendingDownIcon />
          -20%
        </Badge>
      </Card.Action>
    </Card.Header>
    <Card.Footer class="flex-col items-start gap-1.5 text-sm">
      <div class="line-clamp-1 flex gap-2 font-medium">
        Down 20% this period <TrendingDownIcon class="size-4" />
      </div>
      <div class="text-muted-foreground">Acquisition needs attention</div>
    </Card.Footer>
  </Card.Root>
  <Card.Root class="@container/card">
    <Card.Header>
      <Card.Description>Active Accounts</Card.Description>
      <Card.Title
        class="text-2xl font-semibold tabular-nums @[250px]/card:text-3xl"
      >
        45,678
      </Card.Title>
      <Card.Action>
        <Badge variant="outline">
          <TrendingUpIcon />
          +12.5%
        </Badge>
      </Card.Action>
    </Card.Header>
    <Card.Footer class="flex-col items-start gap-1.5 text-sm">
      <div class="line-clamp-1 flex gap-2 font-medium">
        Strong user retention <TrendingUpIcon class="size-4" />
      </div>
      <div class="text-muted-foreground">Engagement exceed targets</div>
    </Card.Footer>
  </Card.Root>
  <Card.Root class="@container/card">
    <Card.Header>
      <Card.Description>Growth Rate</Card.Description>
      <Card.Title
        class="text-2xl font-semibold tabular-nums @[250px]/card:text-3xl"
      >
        4.5%
      </Card.Title>
      <Card.Action>
        <Badge variant="outline">
          <TrendingUpIcon />
          +4.5%
        </Badge>
      </Card.Action>
    </Card.Header>
    <Card.Footer class="flex-col items-start gap-1.5 text-sm">
      <div class="line-clamp-1 flex gap-2 font-medium">
        Steady performance increase <TrendingUpIcon class="size-4" />
      </div>
      <div class="text-muted-foreground">Meets growth projections</div>
    </Card.Footer>
  </Card.Root>
</div>
